spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bikec?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  profiles:
    active: local #local
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10 #page default size? 10??
        max-page-size: 2000 #?? ??? size

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
